//! Translates the typed IR into a single C23 translation unit.
//!
//! The IR is already sequenced and free of hidden control flow, so this is a
//! direct printer: types become typedefs, functions become `static`
//! functions taking the context pointer, and statements map one to one.

mod cconv;
mod helpers;
mod statics;
mod type_info;
mod types;

use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;

use wid_diagnostics::{SourceMap, Span};
use wid_sema::ir::{self, Builtin, ExprKind, FnId, LabelId, LocalId, Program, Stmt};
use wid_sema::types::{Abi, FloatTy, IntTy, TyId, TyKind, TypeTable};

pub use cconv::implementation_unit;
use cconv::{c_includes, is_lvalue};

/// The first line of every C file the compiler generates.
pub const GENERATED_HEADER: &str = "/* Generated by the Wid compiler. Do not edit. */";

/// Options for C generation.
#[derive(Clone, Debug, Default)]
pub struct Options {
    /// Emit `#line` directives that map C back to Wid sources.
    pub line_directives: bool,
    /// The name of the runtime header to include.
    pub runtime_header: String,
}

/// Generates the C source for a checked program.
pub fn generate(program: &Program, sources: &SourceMap, opts: &Options) -> String {
    let mut g = Gen {
        p: program,
        sources,
        opts,
        type_names: HashMap::new(),
        defined: HashSet::new(),
        typedefs: String::new(),
        used_names: HashSet::new(),
        helpers_done: HashSet::new(),
        vector_helpers: HashSet::new(),
        helper_protos: String::new(),
        helper_bodies: String::new(),
        fn_name: String::new(),
        locals: Vec::new(),
        type_infos: Vec::new(),
        type_info_index: HashMap::new(),
        type_info_struct: None,
    };
    g.emit()
}

struct Gen<'p> {
    p: &'p Program,
    sources: &'p SourceMap,
    opts: &'p Options,
    type_names: HashMap<TyId, String>,
    defined: HashSet<TyId>,
    typedefs: String,
    used_names: HashSet<String>,
    /// Helper functions already generated, by kind and type.
    helpers_done: HashSet<(&'static str, TyId)>,
    /// Element-wise operator helpers already generated, by name.
    vector_helpers: HashSet<String>,
    helper_protos: String,
    helper_bodies: String,
    /// The Wid name of the function being emitted, for locations.
    fn_name: String,
    /// C names of the locals of the function being emitted.
    locals: Vec<String>,
    /// The types `type_info` describes, in table order.
    type_infos: Vec<TyId>,
    /// Each described type's index in `type_infos`.
    type_info_index: HashMap<TyId, usize>,
    /// The prelude's `TypeInfo`, once a function uses `type_info`.
    type_info_struct: Option<TyId>,
}

impl<'p> Gen<'p> {
    fn emit(&mut self) -> String {
        let reachable = self.reachable();
        let mut protos = String::new();
        let mut bodies = String::new();
        for (i, f) in self.p.functions.iter().enumerate() {
            if !reachable.contains(&FnId(i as u32)) {
                continue;
            }
            if let Some(foreign) = &f.foreign {
                // The runtime header declares every `wid_` symbol, and an
                // included C header declares the imported functions.
                if foreign.starts_with("wid_") || f.c_call.is_some() {
                    continue;
                }
                let ret = self.c_type(f.ret);
                let mut params: Vec<String> = f.params.iter().map(|p| self.c_type(f.locals[p.0 as usize].ty)).collect();
                if f.c_variadic {
                    params.push("...".to_string());
                }
                let params = if params.is_empty() { "void".to_string() } else { params.join(", ") };
                let noreturn = if matches!(self.p.types.kind(f.ret), TyKind::Never) { "[[noreturn]] " } else { "" };
                // Declared under a name of its own and bound to the C symbol, so it
                // can't conflict with a C header's declaration of the same function.
                let alias = extern_alias(foreign);
                let _ =
                    writeln!(protos, "{noreturn}extern {ret} {alias}({params}) __asm__(WID_SYMBOL(\"{foreign}\"));");
                continue;
            }
            let sig = self.signature(f, None);
            let _ = writeln!(protos, "{sig};");
            if let Some(body) = &f.body {
                self.function_body(f, body, &mut bodies);
            }
        }

        let emitted: Vec<&ir::Function> = (0..self.p.functions.len())
            .filter(|i| reachable.contains(&FnId(*i as u32)))
            .map(|i| &self.p.functions[i])
            .collect();
        let used = self.used_globals(&emitted);
        let statics = self.static_globals(&used);
        let type_infos = self.type_info_table();

        let mut out = String::new();
        out.push_str(GENERATED_HEADER);
        out.push('\n');
        out.push_str("#define WID_RUNTIME_IMPLEMENTATION\n");
        if self.p.debug {
            out.push_str("#define WID_DEBUG 1\n");
        }
        let _ = writeln!(out, "#include \"{}\"", self.opts.runtime_header);
        out.push_str(&c_includes(&self.p.c_includes));
        out.push('\n');
        out.push_str(&self.typedefs);
        out.push('\n');
        out.push_str(&self.helper_protos);
        out.push_str(&protos);
        out.push('\n');
        out.push_str(&statics);
        out.push_str(&type_infos);
        out.push_str(&self.helper_bodies);
        out.push_str(&bodies);
        if let (false, Some(runner)) = (self.p.tests.is_empty(), self.p.test_runner) {
            self.test_main(runner, &mut out);
        } else if let Some(main) = self.p.main {
            let name = &self.p.functions[main.0 as usize].c_name;
            out.push_str("int main(int argc, char **argv) {\n");
            out.push_str("    wid_runtime_init(argc, argv);\n");
            out.push_str("    wid_Context ctx = wid_default_context();\n");
            let _ = writeln!(out, "    {name}(&ctx);");
            out.push_str("    wid_runtime_exit();\n");
            out.push_str("    return 0;\n");
            out.push_str("}\n");
        }
        out
    }

    /// Emits the `main` of a test build: `--list` prints the test names, and
    /// an index runs that test through `core:testing`'s runner, exiting with 0
    /// when it passed and 1 when it failed.
    fn test_main(&mut self, runner: FnId, out: &mut String) {
        let runner_name = self.p.functions[runner.0 as usize].c_name.clone();
        out.push_str("int main(int argc, char **argv) {\n");
        out.push_str("    wid_runtime_init(argc, argv);\n");
        out.push_str("    wid_Context ctx = wid_default_context();\n");
        out.push_str("    static const char *const names[] = {\n");
        for t in &self.p.tests {
            let _ = writeln!(out, "        {},", c_string_literal(t.name.as_bytes()));
        }
        out.push_str("    };\n");
        out.push_str("    if (argc == 2 && strcmp(argv[1], \"--list\") == 0) {\n");
        out.push_str("        for (size_t i = 0; i < sizeof names / sizeof names[0]; i++) puts(names[i]);\n");
        out.push_str("        return 0;\n");
        out.push_str("    }\n");
        out.push_str("    char *end = nullptr;\n");
        out.push_str("    long index = argc == 2 ? strtol(argv[1], &end, 10) : -1;\n");
        out.push_str("    if (argc != 2 || *end != '\\0') index = -1;\n");
        out.push_str("    bool passed = false;\n");
        out.push_str("    switch (index) {\n");
        for (i, t) in self.p.tests.iter().enumerate() {
            let f = &self.p.functions[t.func.0 as usize].c_name;
            let _ = writeln!(
                out,
                "    case {i}: passed = {runner_name}(&ctx, wid_string_from_cstring(names[{i}]), {f}); break;"
            );
        }
        out.push_str("    default:\n");
        out.push_str("        fputs(\"usage: <test binary> --list | <test index>\\n\", stderr);\n");
        out.push_str("        return 2;\n");
        out.push_str("    }\n");
        out.push_str("    wid_runtime_exit();\n");
        out.push_str("    return passed ? 0 : 1;\n");
        out.push_str("}\n");
    }

    /// Finds every function reachable from `main`, the tests and exported
    /// functions.
    fn reachable(&self) -> HashSet<FnId> {
        let mut seen = HashSet::new();
        let mut stack: Vec<FnId> = self.p.main.into_iter().collect();
        stack.extend(self.p.tests.iter().map(|t| t.func));
        stack.extend(self.p.test_runner);
        for (i, f) in self.p.functions.iter().enumerate() {
            if f.export.is_some() || (self.p.main.is_none() && self.p.tests.is_empty()) {
                stack.push(FnId(i as u32));
            }
        }
        let mut globals_seen = HashSet::new();
        let mut globals = Vec::new();
        loop {
            while let Some(id) = stack.pop() {
                if self.p.functions[id.0 as usize].comptime_only || !seen.insert(id) {
                    continue;
                }
                if let Some(body) = &self.p.functions[id.0 as usize].body {
                    visit_block(body, &mut |e| match &e.kind {
                        ExprKind::Call { func, .. } | ExprKind::FnRef(func) => stack.push(*func),
                        ExprKind::Global(g) | ExprKind::ConstGlobal(g) => globals.push(*g),
                        _ => {}
                    });
                }
            }
            // Procs stored in compile-time constants are reachable too.
            let Some(g) = globals.pop() else { break };
            if !globals_seen.insert(g) {
                continue;
            }
            if let Some(init) = &self.p.globals[g.0 as usize].init {
                visit_expr(init, &mut |e| match &e.kind {
                    ExprKind::FnRef(func) => stack.push(*func),
                    ExprKind::Global(g) | ExprKind::ConstGlobal(g) => globals.push(*g),
                    _ => {}
                });
            }
        }
        seen
    }

    /// The C declarator of a function. With `reads`, parameters the body
    /// never reads are marked `[[maybe_unused]]`, as Wid allows them.
    fn signature(&mut self, f: &ir::Function, reads: Option<&HashSet<LocalId>>) -> String {
        let ret = self.c_type(f.ret);
        let mut params = Vec::new();
        if f.abi == Abi::Wid {
            params.push("[[maybe_unused]] wid_Context *ctx".to_string());
        }
        for &p in &f.params {
            let local = &f.locals[p.0 as usize];
            let ty = self.c_type(local.ty);
            let attr = if reads.is_some_and(|r| !r.contains(&p)) { "[[maybe_unused]] " } else { "" };
            params.push(format!("{attr}{ty} {}", local_name(local, p)));
        }
        if params.is_empty() {
            params.push("void".into());
        }
        let linkage = if f.export.is_some() { "" } else { "static " };
        let noreturn = if matches!(self.p.types.kind(f.ret), TyKind::Never) { "[[noreturn]] " } else { "" };
        let name = f.export.as_deref().unwrap_or(&f.c_name);
        format!("{noreturn}{linkage}{ret} {name}({})", params.join(", "))
    }

    fn function_body(&mut self, f: &ir::Function, body: &ir::Block, out: &mut String) {
        self.fn_name = f.display.clone();
        self.locals = f.locals.iter().enumerate().map(|(i, l)| local_name(l, LocalId(i as u32))).collect();
        let mut used_labels = HashSet::new();
        collect_gotos(body, &mut used_labels);
        let mut reads = HashSet::new();
        collect_reads(body, &self.p.types, &mut reads);
        let sig = self.signature(f, Some(&reads));
        let mut ctx = FnCtx { contexts: 0, used_labels, reads, out: String::new(), indent: 1 };
        let _ = writeln!(out, "{sig} {{");
        if f.abi == Abi::C {
            ctx.out.push_str(
                "    wid_Context ctx_ = wid_default_context();\n    [[maybe_unused]] wid_Context *ctx = &ctx_;\n",
            );
        }
        self.block_stmts(body, &mut ctx, f);
        out.push_str(&ctx.out);
        out.push_str("}\n\n");
    }

    fn block_stmts(&mut self, block: &ir::Block, ctx: &mut FnCtx, f: &ir::Function) {
        for stmt in &block.stmts {
            self.stmt(stmt, ctx, f);
        }
    }

    fn line(&self, ctx: &mut FnCtx, text: &str) {
        for _ in 0..ctx.indent {
            ctx.out.push_str("    ");
        }
        ctx.out.push_str(text);
        ctx.out.push('\n');
    }

    fn nested(&mut self, block: &ir::Block, ctx: &mut FnCtx, f: &ir::Function) {
        ctx.indent += 1;
        self.block_stmts(block, ctx, f);
        ctx.indent -= 1;
    }

    fn stmt(&mut self, stmt: &Stmt, ctx: &mut FnCtx, f: &ir::Function) {
        match stmt {
            Stmt::Let { local, init } => {
                let ty = f.locals[local.0 as usize].ty;
                let cty = self.c_type(ty);
                let attr = if ctx.reads.contains(local) { "" } else { "[[maybe_unused]] " };
                let name = &self.locals[local.0 as usize].clone();
                let value = match init {
                    Some(e) => self.expr(e),
                    None => "{}".to_string(),
                };
                let text = format!("{attr}{cty} {name} = {value};");
                self.line(ctx, &text);
            }
            Stmt::LetUninit(local) => {
                let ty = f.locals[local.0 as usize].ty;
                let cty = self.c_type(ty);
                let attr = if ctx.reads.contains(local) { "" } else { "[[maybe_unused]] " };
                let text = format!("{attr}{cty} {};", self.locals[local.0 as usize]);
                self.line(ctx, &text);
            }
            Stmt::Assign { target, value } => {
                let text = format!("{} = {};", self.expr(target), self.expr(value));
                self.line(ctx, &text);
            }
            Stmt::Expr(e) => {
                let text = format!("{};", self.expr(e));
                self.line(ctx, &text);
            }
            Stmt::If { cond, then, else_ } => {
                let text = format!("if ({}) {{", strip_parens(&self.expr(cond)));
                self.line(ctx, &text);
                self.nested(then, ctx, f);
                if else_.stmts.is_empty() {
                    self.line(ctx, "}");
                } else if let [nested @ Stmt::If { .. }] = else_.stmts.as_slice() {
                    ctx.out.push_str(&"    ".repeat(ctx.indent));
                    ctx.out.push_str("} else ");
                    let start = ctx.out.len();
                    let saved = ctx.indent;
                    self.stmt(nested, ctx, f);
                    let trimmed: String = ctx.out[start..].trim_start().to_string();
                    ctx.out.truncate(start);
                    ctx.out.push_str(&trimmed);
                    ctx.indent = saved;
                } else {
                    self.line(ctx, "} else {");
                    self.nested(else_, ctx, f);
                    self.line(ctx, "}");
                }
            }
            Stmt::Loop { body, continue_label, break_label } => {
                self.line(ctx, "for (;;) {");
                self.nested(body, ctx, f);
                if ctx.used_labels.contains(continue_label) {
                    ctx.indent += 1;
                    self.line(ctx, &format!("{}:;", label_name(*continue_label)));
                    ctx.indent -= 1;
                }
                self.line(ctx, "}");
                if ctx.used_labels.contains(break_label) {
                    self.line(ctx, &format!("{}:;", label_name(*break_label)));
                }
            }
            Stmt::Labeled { body, end_label } => {
                self.line(ctx, "{");
                self.nested(body, ctx, f);
                self.line(ctx, "}");
                if ctx.used_labels.contains(end_label) {
                    self.line(ctx, &format!("{}:;", label_name(*end_label)));
                }
            }
            Stmt::WithContext(body) => {
                ctx.contexts += 1;
                let n = ctx.contexts;
                self.line(ctx, "{");
                self.line(ctx, &format!("    wid_Context ctx_{n} = *ctx;"));
                self.line(ctx, &format!("    [[maybe_unused]] wid_Context *ctx = &ctx_{n};"));
                self.nested(body, ctx, f);
                self.line(ctx, "}");
            }
            Stmt::Scope(body) => {
                self.line(ctx, "{");
                self.nested(body, ctx, f);
                self.line(ctx, "}");
            }
            Stmt::Goto(label) => self.line(ctx, &format!("goto {};", label_name(*label))),
            Stmt::Return(value) => match value {
                Some(v) => {
                    let text = format!("return {};", strip_parens(&self.expr(v)));
                    self.line(ctx, &text);
                }
                None => self.line(ctx, "return;"),
            },
            Stmt::Unreachable => self.line(ctx, "unreachable();"),
            Stmt::Line(span) => {
                if self.opts.line_directives {
                    let file = self.sources.file(span.file);
                    let (line, _) = file.line_col(span.start);
                    ctx.out.push_str(&format!("#line {line} {}\n", c_string_literal(file.display.as_bytes())));
                }
            }
        }
    }

    fn location(&self, span: Span) -> String {
        let file = self.sources.file(span.file);
        let (line, col) = file.line_col(span.start);
        format!(
            "WID_LOC({}, {line}, {col}, {})",
            c_string_literal(file.display.as_bytes()),
            c_string_literal(self.fn_name.as_bytes())
        )
    }

    fn expr(&mut self, e: &ir::Expr) -> String {
        match &e.kind {
            ExprKind::Int(v) => self.int_literal(*v, e.ty),
            ExprKind::Float(v) => float_literal(*v, self.float_kind(e.ty)),
            ExprKind::Bool(b) => if *b { "true" } else { "false" }.to_string(),
            ExprKind::Str(s) => match self.p.types.kind(self.p.types.base(e.ty)) {
                TyKind::CString => c_string_literal(s.as_bytes()),
                _ => format!("WID_STR({})", c_string_literal(s.as_bytes())),
            },
            ExprKind::Nil => self.nil_value(e.ty),
            ExprKind::Zero => self.zero_value(e.ty),
            ExprKind::Local(l) => self.locals[l.0 as usize].clone(),
            ExprKind::Global(g) => {
                let global = &self.p.globals[g.0 as usize];
                let name = global.c_name.clone();
                match global.c_conv.clone() {
                    Some(conv) => self.conv_from_c(&conv, &name, e.ty),
                    None => name,
                }
            }
            ExprKind::ConstGlobal(g) => self.p.globals[g.0 as usize].c_name.clone(),
            ExprKind::FnRef(f) => {
                let func = &self.p.functions[f.0 as usize];
                match (&func.foreign, &func.c_call) {
                    (Some(symbol), Some(_)) => {
                        let symbol = symbol.clone();
                        let ty = self.c_type(e.ty);
                        format!("(({ty}){symbol})")
                    }
                    _ => call_name(func),
                }
            }
            ExprKind::Field { base, index } => {
                // Member access needs the complete type, even behind a pointer.
                self.c_type(base.ty);
                if let ExprKind::Deref(ptr) = &base.kind {
                    let p = self.expr(ptr);
                    return self.field_access(&p, true, true, base.ty, *index);
                }
                let lvalue = is_lvalue(base);
                let b = self.expr(base);
                self.field_access(&b, false, lvalue, base.ty, *index)
            }
            ExprKind::Deref(inner) => {
                self.c_type(e.ty);
                format!("(*{})", self.expr(inner))
            }
            ExprKind::AddrOf(inner) => format!("(&{})", self.expr(inner)),
            ExprKind::Call { func, args } => {
                let f = &self.p.functions[func.0 as usize];
                let name = call_name(f);
                let c_call = f.c_call.clone();
                let mut parts = Vec::new();
                if f.abi == Abi::Wid {
                    parts.push("ctx".to_string());
                }
                for (i, a) in args.iter().enumerate() {
                    let v = self.expr(a);
                    let v = match c_call.as_ref().and_then(|c| c.params.get(i).cloned().flatten()) {
                        Some(conv) => self.conv_to_c(&conv, &v, a.ty),
                        None => v,
                    };
                    parts.push(strip_parens(&v).to_string());
                }
                let call = format!("{name}({})", parts.join(", "));
                match c_call.and_then(|c| c.ret) {
                    Some(conv) => self.conv_from_c(&conv, &call, e.ty),
                    None => call,
                }
            }
            ExprKind::CallIndirect { callee, args, span } => {
                let c = self.expr(callee);
                let wid_abi = match self.p.types.kind(self.p.types.base(callee.ty)) {
                    TyKind::Proc(sig) => sig.abi == Abi::Wid,
                    _ => true,
                };
                let mut parts = if wid_abi { vec!["ctx".to_string()] } else { Vec::new() };
                for a in args {
                    parts.push(strip_parens(&self.expr(a)).to_string());
                }
                let loc = self.location(*span);
                format!("(({c}) ? (void)0 : wid_nil_panic({loc}), {c}({}))", parts.join(", "))
            }
            ExprKind::Builtin { op, args, span } => self.builtin(*op, args, *span, e.ty),
            ExprKind::Unary { op, expr } => {
                let v = self.expr(expr);
                match op {
                    ir::UnaryOp::Neg => format!("(-{v})"),
                    ir::UnaryOp::Not => format!("(!{v})"),
                    ir::UnaryOp::BitNot => {
                        let ty = self.c_type(e.ty);
                        format!("(({ty})~{v})")
                    }
                }
            }
            ExprKind::Binary { op, lhs, rhs, span } => self.binary(*op, lhs, rhs, *span, e.ty),
            ExprKind::Cast { expr, .. } => {
                let ty = self.c_type(e.ty);
                format!("(({ty}){})", self.expr(expr))
            }
            ExprKind::Select { cond, then, else_ } => {
                format!("({} ? {} : {})", self.expr(cond), self.expr(then), self.expr(else_))
            }
            ExprKind::Context => "ctx".to_string(),
            ExprKind::Aggregate(elems) => self.aggregate(e.ty, elems),
            ExprKind::OptSome(inner) => {
                let v = self.expr(inner);
                if self.p.types.optional_is_pointer(e.ty) {
                    v
                } else {
                    let cty = self.c_type(e.ty);
                    format!("(({cty}){{.value = {}, .has = true}})", strip_parens(&v))
                }
            }
            ExprKind::OptIsSome(inner) => {
                let v = self.expr(inner);
                if self.p.types.optional_is_pointer(inner.ty) {
                    format!("({v} != nullptr)")
                } else {
                    format!("{v}.has")
                }
            }
            ExprKind::UnionWrap { variant, value } => {
                let cty = self.c_type(e.ty);
                let v = self.expr(value);
                format!("(({cty}){{.tag = {}, .as.v{variant} = {}}})", variant + 1, strip_parens(&v))
            }
            ExprKind::UnionTag(inner) => format!("{}.tag", self.expr(inner)),
            ExprKind::UnionGet { value, variant } => format!("{}.as.v{variant}", self.expr(value)),
            ExprKind::Index { base, index, checked, span } => {
                let b = self.expr(base);
                let i = strip_parens(&self.expr(index)).to_string();
                let base_ty = self.p.types.base(base.ty);
                let (data, len) = match self.p.types.kind(base_ty).clone() {
                    TyKind::Array(_, n) => (format!("{b}.data"), format!("INT64_C({n})")),
                    TyKind::Matrix(_, r, c) => {
                        (format!("{b}.data"), format!("INT64_C({})", u64::from(r) * u64::from(c)))
                    }
                    TyKind::MultiPointer(_) => (b.clone(), String::new()),
                    _ => (format!("{b}.data"), format!("{b}.len")),
                };
                if *checked && !len.is_empty() {
                    let loc = self.location(*span);
                    format!("{data}[wid_bounds({i}, {len}, {loc})]")
                } else {
                    format!("{data}[{i}]")
                }
            }
            ExprKind::SliceOf { base, lo, hi, checked, span } => {
                let b = self.expr(base);
                let lo = strip_parens(&self.expr(lo)).to_string();
                let hi = strip_parens(&self.expr(hi)).to_string();
                let base_ty = self.p.types.base(base.ty);
                let (data, len) = match self.p.types.kind(base_ty).clone() {
                    TyKind::Array(_, n) => (format!("{b}.data"), format!("INT64_C({n})")),
                    TyKind::MultiPointer(_) => (b.clone(), String::new()),
                    _ => (format!("{b}.data"), format!("{b}.len")),
                };
                let cty = self.c_type(e.ty);
                let view = if matches!(self.p.types.kind(e.ty), TyKind::String) {
                    format!("((wid_String){{{data} + ({lo}), ({hi}) - ({lo})}})")
                } else {
                    format!("(({cty}){{.data = {data} + ({lo}), .len = ({hi}) - ({lo})}})")
                };
                if *checked && !len.is_empty() {
                    let loc = self.location(*span);
                    format!("(wid_slice_check({lo}, {hi}, {len}, {loc}), {view})")
                } else {
                    view
                }
            }
            ExprKind::OptGet(inner) => {
                let v = self.expr(inner);
                if self.p.types.optional_is_pointer(inner.ty) { v } else { format!("{v}.value") }
            }
            ExprKind::ErrorTag(name) => {
                let index = self.p.errors.iter().position(|n| n == name).map_or(0, |i| i + 1);
                format!("((wid_Error){index})")
            }
        }
    }

    fn field_name(&self, ty: TyId, index: u32) -> String {
        match self.p.types.kind(ty) {
            TyKind::Struct(id) => {
                let info = self.p.types.struct_info(*id);
                let field = &info.fields[index as usize];
                match (&field.c_name, info.foreign) {
                    (Some(c), _) => c.clone(),
                    (None, true) => field.name.as_str().to_string(),
                    (None, false) => types::field_ident(field.name.as_str()),
                }
            }
            TyKind::Dynamic(_) => ["data", "len", "cap", "allocator"][index as usize].to_string(),
            TyKind::Slice(_) => ["data", "len"][index as usize].to_string(),
            _ => format!("f{index}"),
        }
    }

    fn int_kind(&self, ty: TyId) -> Option<IntTy> {
        match self.p.types.kind(self.p.types.base(ty)) {
            TyKind::Int(i) => Some(*i),
            TyKind::Enum(id) => Some(self.p.types.enum_info(*id).backing),
            _ => None,
        }
    }

    fn float_kind(&self, ty: TyId) -> FloatTy {
        match self.p.types.kind(self.p.types.base(ty)) {
            TyKind::Float(f) => *f,
            _ => FloatTy::F64,
        }
    }

    fn int_literal(&mut self, v: i128, ty: TyId) -> String {
        match self.p.types.kind(self.p.types.base(ty)) {
            TyKind::Float(f) => return float_literal(v as f64, *f),
            TyKind::Bool => return if v != 0 { "true".into() } else { "false".into() },
            TyKind::Rune => return format!("((wid_Rune){v})"),
            _ => {}
        }
        match self.int_kind(ty) {
            Some(IntTy::I64 | IntTy::Int) => {
                if v == i128::from(i64::MIN) {
                    "INT64_MIN".into()
                } else {
                    format!("INT64_C({v})")
                }
            }
            Some(IntTy::U64 | IntTy::UInt) => format!("UINT64_C({v})"),
            Some(_) | None => {
                let cty = self.c_type(ty);
                format!("(({cty}){v})")
            }
        }
    }

    fn nil_value(&mut self, ty: TyId) -> String {
        match self.p.types.kind(self.p.types.base(ty)) {
            TyKind::Error => "((wid_Error)0)".into(),
            TyKind::Pointer(_) | TyKind::MultiPointer(_) | TyKind::RawPtr | TyKind::CString | TyKind::Proc(_) => {
                "nullptr".into()
            }
            _ if self.p.types.optional_is_pointer(ty) => "nullptr".into(),
            _ => format!("(({}){{}})", self.c_type(ty)),
        }
    }

    fn zero_value(&mut self, ty: TyId) -> String {
        match self.p.types.kind(self.p.types.base(ty)) {
            TyKind::Bool => "false".into(),
            TyKind::Int(_)
            | TyKind::Enum(_)
            | TyKind::Rune
            | TyKind::Error
            | TyKind::TypeId
            | TyKind::Type
            | TyKind::Code
            | TyKind::Symbol => "0".into(),
            TyKind::Float(FloatTy::F32) => "0.0f".into(),
            TyKind::Float(FloatTy::F64) => "0.0".into(),
            TyKind::Pointer(_) | TyKind::MultiPointer(_) | TyKind::RawPtr | TyKind::CString | TyKind::Proc(_) => {
                "nullptr".into()
            }
            TyKind::Void | TyKind::Never | TyKind::Unknown => "((void)0)".into(),
            _ => format!("(({}){{}})", self.c_type(ty)),
        }
    }

    fn int_suffix(&self, ty: TyId) -> &'static str {
        match self.int_kind(ty) {
            Some(IntTy::I8) => "i8",
            Some(IntTy::I16) => "i16",
            Some(IntTy::I32) => "i32",
            Some(IntTy::I64 | IntTy::Int) => "i64",
            Some(IntTy::U8) => "u8",
            Some(IntTy::U16) => "u16",
            Some(IntTy::U32) => "u32",
            Some(IntTy::U64 | IntTy::UInt) | None => "u64",
        }
    }

    fn binary(&mut self, op: ir::BinaryOp, lhs: &ir::Expr, rhs: &ir::Expr, span: Span, ty: TyId) -> String {
        use ir::BinaryOp as B;
        let l = self.expr(lhs);
        let r = self.expr(rhs);
        let shaped = |t: TyId| matches!(self.p.types.kind(t), TyKind::Array(..) | TyKind::Matrix(..));
        let is_matrix = |t: TyId| matches!(self.p.types.kind(t), TyKind::Matrix(..));
        if op == B::Mul && shaped(lhs.ty) && shaped(rhs.ty) && (is_matrix(lhs.ty) || is_matrix(rhs.ty)) {
            let name = self.matrix_product_helper(lhs.ty, rhs.ty, ty);
            return format!("{name}({}, {})", strip_parens(&l), strip_parens(&r));
        }
        if (shaped(lhs.ty) || shaped(rhs.ty)) && !matches!(op, B::Eq | B::Ne) {
            let name = self.vector_helper(op, lhs.ty, rhs.ty, ty);
            return format!("{name}({}, {})", strip_parens(&l), strip_parens(&r));
        }
        if op == B::Cmp {
            return format!("((wid_Int)(({l}) > ({r})) - (wid_Int)(({l}) < ({r})))");
        }
        if op == B::Pow {
            return match self.p.types.kind(self.p.types.base(lhs.ty)) {
                TyKind::Float(FloatTy::F32) => format!("powf({}, {})", strip_parens(&l), strip_parens(&r)),
                TyKind::Float(_) => format!("pow({}, {})", strip_parens(&l), strip_parens(&r)),
                _ => {
                    let s = self.int_suffix(lhs.ty);
                    let loc = self.location(span);
                    format!("wid_pow_{s}({}, {}, {loc})", strip_parens(&l), strip_parens(&r))
                }
            };
        }
        let is_int = self.int_kind(lhs.ty).is_some() && !matches!(self.p.types.kind(lhs.ty), TyKind::Enum(_));
        if is_int {
            let s = self.int_suffix(lhs.ty);
            match op {
                B::Div | B::Rem => {
                    let name = if op == B::Div { "div" } else { "rem" };
                    let loc = self.location(span);
                    return format!("wid_{name}_{s}({}, {}, {loc})", strip_parens(&l), strip_parens(&r));
                }
                B::Shl | B::Shr => {
                    let name = if op == B::Shl { "shl" } else { "shr" };
                    return format!("wid_{name}_{s}({}, (uint64_t)({}))", strip_parens(&l), strip_parens(&r));
                }
                B::Add | B::Sub | B::Mul if self.p.checks.overflow => {
                    let name = match op {
                        B::Add => "add",
                        B::Sub => "sub",
                        _ => "mul",
                    };
                    let loc = self.location(span);
                    return format!("wid_{name}_{s}({}, {}, {loc})", strip_parens(&l), strip_parens(&r));
                }
                B::Add | B::Sub | B::Mul | B::BitAnd | B::BitOr | B::BitXor => {
                    // Narrow integer types promote to `int` in C; cast back.
                    let sym = c_binop(op);
                    let size = self.int_kind(lhs.ty).map_or(8, IntTy::size);
                    if size < 4 {
                        let cty = self.c_type(ty);
                        return format!("(({cty})({l} {sym} {r}))");
                    }
                    return format!("({l} {sym} {r})");
                }
                _ => {}
            }
        }
        let base = self.p.types.base(lhs.ty);
        let compound = matches!(
            self.p.types.kind(base),
            TyKind::String | TyKind::Struct(_) | TyKind::Array(..) | TyKind::Matrix(..) | TyKind::Tuple(_)
        ) || matches!(self.p.types.kind(base), TyKind::Optional(_))
            && !self.p.types.optional_is_pointer(base);
        if compound && matches!(op, B::Eq | B::Ne) {
            let eq = self.eq_expr(lhs.ty, strip_parens(&l), strip_parens(&r));
            return if op == B::Eq { eq } else { format!("(!{eq})") };
        }
        if matches!(self.p.types.kind(self.p.types.base(lhs.ty)), TyKind::Float(_)) && op == B::Rem {
            let f = if matches!(self.float_kind(lhs.ty), FloatTy::F32) { "fmodf" } else { "fmod" };
            return format!("{f}({}, {})", strip_parens(&l), strip_parens(&r));
        }
        format!("({l} {} {r})", c_binop(op))
    }

    fn builtin(&mut self, op: Builtin, args: &[ir::Expr], span: Span, ty: TyId) -> String {
        match op {
            Builtin::Print { newline, inspect } => {
                let mut parts = Vec::new();
                for a in args {
                    parts.push(self.print_value(a, inspect, "wid_stdout()"));
                }
                if newline {
                    parts.push(r"wid_w_char(wid_stdout(), '\n')".into());
                }
                if parts.len() == 1 { parts.pop().unwrap_or_default() } else { format!("({})", parts.join(", ")) }
            }
            Builtin::Panic => {
                let msg = self.expr(&args[0]);
                format!("wid_panic({}, {})", strip_parens(&msg), self.location(span))
            }
            Builtin::Assert => {
                let cond = self.expr(&args[0]);
                let msg = self.expr(&args[1]);
                format!("wid_assert({}, {}, {})", strip_parens(&cond), strip_parens(&msg), self.location(span))
            }
            Builtin::SizeOf => {
                let ty = self.c_type(args[0].ty);
                format!("((wid_Int)sizeof({ty}))")
            }
            Builtin::Len => {
                let v = self.expr(&args[0]);
                match self.p.types.kind(self.p.types.base(args[0].ty)) {
                    TyKind::Map(..) => format!("({v}).raw.len"),
                    TyKind::Array(_, n) => format!("INT64_C({n})"),
                    _ => format!("({v}).len"),
                }
            }
            Builtin::TypeInfo => self.type_info_ref(args[0].ty, ty),
            Builtin::BuilderNew => {
                let a = self.expr(&args[0]);
                format!("wid_builder({})", strip_parens(&a))
            }
            Builtin::Write { inspect } => {
                let w = self.expr(&args[0]);
                let v = strip_parens(&self.expr(&args[1])).to_string();
                self.print_expr(args[1].ty, &v, inspect, strip_parens(&w))
            }
            Builtin::BuilderString => {
                let w = self.expr(&args[0]);
                format!("wid_builder_string({})", strip_parens(&w))
            }
            Builtin::DefaultContext => "wid_default_context()".into(),
            Builtin::Alloc => {
                let TyKind::Pointer(inner) = self.p.types.kind(ty).clone() else { return "nullptr".into() };
                let t = self.c_type(inner);
                let a = self.expr(&args[0]);
                let loc = self.location(span);
                format!("(({t} *)wid_alloc({}, (wid_Int)sizeof({t}), (wid_Int)alignof({t}), {loc}))", strip_parens(&a))
            }
            Builtin::AllocSlice => {
                let TyKind::Slice(inner) = self.p.types.kind(ty).clone() else { return "nullptr".into() };
                let st = self.c_type(ty);
                let t = self.c_type(inner);
                let n = self.expr(&args[0]);
                let a = self.expr(&args[1]);
                let loc = self.location(span);
                format!(
                    "(({st}){{.data = wid_alloc_array({}, {n}, (wid_Int)sizeof({t}), (wid_Int)alignof({t}), {loc}), .len = {n}}})",
                    strip_parens(&a)
                )
            }
            Builtin::Free => {
                let loc = self.location(span);
                let v = strip_parens(&self.expr(&args[0])).to_string();
                match self.p.types.kind(args[0].ty).clone() {
                    TyKind::Pointer(inner) => match self.p.types.kind(inner).clone() {
                        TyKind::Dynamic(elem) => {
                            let t = self.c_type(elem);
                            format!("wid_dyn_free((wid_RawDyn *)({v}), (wid_Int)sizeof({t}), {loc})")
                        }
                        TyKind::Map(..) => {
                            let info = self.map_info(inner);
                            format!("wid_map_free((wid_RawMap *)({v}), &{info}, {loc})")
                        }
                        _ => {
                            let t = self.c_type(inner);
                            let a = self.expr(&args[1]);
                            format!("wid_free({}, {v}, (wid_Int)sizeof({t}), {loc})", strip_parens(&a))
                        }
                    },
                    TyKind::Slice(elem) => {
                        let t = self.c_type(elem);
                        let a = self.expr(&args[1]);
                        format!("wid_free({}, ({v}).data, ({v}).len * (wid_Int)sizeof({t}), {loc})", strip_parens(&a))
                    }
                    TyKind::String => {
                        let a = self.expr(&args[1]);
                        format!("wid_free({}, (void *)({v}).data, ({v}).len, {loc})", strip_parens(&a))
                    }
                    TyKind::CString => {
                        let a = self.expr(&args[1]);
                        format!("wid_free({}, {v}, (wid_Int)strlen({v}) + 1, {loc})", strip_parens(&a))
                    }
                    _ => "((void)0)".into(),
                }
            }
            Builtin::FreeAll => {
                let a = self.expr(&args[0]);
                format!("wid_free_all({}, {})", strip_parens(&a), self.location(span))
            }
            Builtin::ToCString => {
                let s = self.expr(&args[0]);
                let a = self.expr(&args[1]);
                format!("wid_string_to_cstring({}, {}, {})", strip_parens(&s), strip_parens(&a), self.location(span))
            }
            Builtin::DynPush | Builtin::DynInsert => {
                let elem = self.container_elem(args[0].ty);
                let t = self.c_type(elem);
                let p = strip_parens(&self.expr(&args[0])).to_string();
                let loc = self.location(span);
                if op == Builtin::DynPush {
                    format!(
                        "(({t} *)wid_dyn_push((wid_RawDyn *)({p}), (wid_Int)sizeof({t}), (wid_Int)alignof({t}), ctx->allocator, {loc}))"
                    )
                } else {
                    let i = strip_parens(&self.expr(&args[1])).to_string();
                    format!(
                        "(({t} *)wid_dyn_insert((wid_RawDyn *)({p}), {i}, (wid_Int)sizeof({t}), (wid_Int)alignof({t}), ctx->allocator, {loc}))"
                    )
                }
            }
            Builtin::DynRemove => {
                let elem = self.container_elem(args[0].ty);
                let t = self.c_type(elem);
                let p = strip_parens(&self.expr(&args[0])).to_string();
                let i = strip_parens(&self.expr(&args[1])).to_string();
                format!("wid_dyn_remove((wid_RawDyn *)({p}), {i}, (wid_Int)sizeof({t}), {})", self.location(span))
            }
            Builtin::DynReserve => {
                let elem = self.container_elem(args[0].ty);
                let t = self.c_type(elem);
                let p = strip_parens(&self.expr(&args[0])).to_string();
                let n = strip_parens(&self.expr(&args[1])).to_string();
                format!(
                    "wid_dyn_reserve((wid_RawDyn *)({p}), {n}, (wid_Int)sizeof({t}), (wid_Int)alignof({t}), ctx->allocator, {})",
                    self.location(span)
                )
            }
            Builtin::DynAppend => {
                let elem = self.container_elem(args[0].ty);
                let t = self.c_type(elem);
                let p = strip_parens(&self.expr(&args[0])).to_string();
                let xs = self.expr(&args[1]);
                format!(
                    "wid_dyn_append((wid_RawDyn *)({p}), ({xs}).data, ({xs}).len, (wid_Int)sizeof({t}), (wid_Int)alignof({t}), ctx->allocator, {})",
                    self.location(span)
                )
            }
            Builtin::DynResize => {
                let elem = self.container_elem(args[0].ty);
                let t = self.c_type(elem);
                let p = strip_parens(&self.expr(&args[0])).to_string();
                let n = strip_parens(&self.expr(&args[1])).to_string();
                format!(
                    "wid_dyn_resize((wid_RawDyn *)({p}), {n}, (wid_Int)sizeof({t}), (wid_Int)alignof({t}), ctx->allocator, {})",
                    self.location(span)
                )
            }
            Builtin::MapPut | Builtin::MapFind | Builtin::MapRemove => {
                let map_ty = self.pointee(args[0].ty);
                let TyKind::Map(k, v) = self.p.types.kind(map_ty).clone() else { return "nullptr".into() };
                let info = self.map_info(map_ty);
                let kt = self.c_type(k);
                let vt = self.c_type(v);
                let p = strip_parens(&self.expr(&args[0])).to_string();
                let key = strip_parens(&self.expr(&args[1])).to_string();
                match op {
                    Builtin::MapPut => {
                        let loc = self.location(span);
                        format!(
                            "(({vt} *)wid_map_put((wid_RawMap *)({p}), &{info}, ({kt}[1]){{{key}}}, ctx->allocator, {loc}))"
                        )
                    }
                    Builtin::MapFind => {
                        format!("(({vt} *)wid_map_find((wid_RawMap *)({p}), &{info}, ({kt}[1]){{{key}}}))")
                    }
                    _ => format!("wid_map_remove((wid_RawMap *)({p}), &{info}, ({kt}[1]){{{key}}})"),
                }
            }
            Builtin::MapNext | Builtin::MapKeyAt | Builtin::MapValueAt => {
                let map_ty = self.pointee(args[0].ty);
                let TyKind::Map(k, v) = self.p.types.kind(map_ty).clone() else { return "0".into() };
                let info = self.map_info(map_ty);
                let p = strip_parens(&self.expr(&args[0])).to_string();
                let i = strip_parens(&self.expr(&args[1])).to_string();
                match op {
                    Builtin::MapNext => format!("wid_map_next((wid_RawMap *)({p}), &{info}, {i})"),
                    Builtin::MapKeyAt => {
                        let kt = self.c_type(k);
                        format!("(({kt} *)wid_map_key((wid_RawMap *)({p}), &{info}, {i}))")
                    }
                    _ => {
                        let vt = self.c_type(v);
                        format!("(({vt} *)wid_map_value((wid_RawMap *)({p}), &{info}, {i}))")
                    }
                }
            }
            Builtin::Utf8Decode => {
                let s = strip_parens(&self.expr(&args[0])).to_string();
                let i = strip_parens(&self.expr(&args[1])).to_string();
                let r = strip_parens(&self.expr(&args[2])).to_string();
                format!("wid_utf8_decode({s}, {i}, {r})")
            }
            Builtin::StringFind => {
                let s = strip_parens(&self.expr(&args[0])).to_string();
                let n = strip_parens(&self.expr(&args[1])).to_string();
                format!("wid_string_find({s}, {n})")
            }
            Builtin::StringBytes => {
                let v = self.expr(&args[0]);
                let ty = self.c_type(ty);
                format!("(({ty}){{(uint8_t *)({v}).data, ({v}).len}})")
            }
            Builtin::SliceData => {
                let v = self.expr(&args[0]);
                format!("(({v}).data)")
            }
            Builtin::BytesString => {
                let v = self.expr(&args[0]);
                format!("((wid_String){{({v}).data, ({v}).len}})")
            }
            Builtin::CallerLocation => self.location(span),
            Builtin::Bounds => {
                let i = strip_parens(&self.expr(&args[0])).to_string();
                let n = strip_parens(&self.expr(&args[1])).to_string();
                format!("wid_bounds({i}, {n}, {})", self.location(span))
            }
            Builtin::CStringString => {
                let v = self.expr(&args[0]);
                format!("wid_string_from_cstring({})", strip_parens(&v))
            }
            Builtin::TypeName
            | Builtin::TypeSize
            | Builtin::TypeAlign
            | Builtin::TypeFields
            | Builtin::Quote { .. }
            | Builtin::ToSymbol => self.zero_value(ty),
            Builtin::StringCmp => {
                let a = self.expr(&args[0]);
                let b = self.expr(&args[1]);
                format!("((int32_t)wid_string_cmp({}, {}))", strip_parens(&a), strip_parens(&b))
            }
        }
    }

    fn print_value(&mut self, v: &ir::Expr, inspect: bool, w: &str) -> String {
        let text = strip_parens(&self.expr(v)).to_string();
        self.print_expr(v.ty, &text, inspect, w)
    }

    /// Returns the element type behind a pointer to a container.
    fn container_elem(&self, ptr: TyId) -> TyId {
        match self.p.types.kind(self.pointee(ptr)) {
            TyKind::Dynamic(e) | TyKind::Slice(e) | TyKind::Array(e, _) => *e,
            _ => ptr,
        }
    }

    fn pointee(&self, ptr: TyId) -> TyId {
        match self.p.types.kind(ptr) {
            TyKind::Pointer(t) => *t,
            _ => ptr,
        }
    }

    fn aggregate(&mut self, ty: TyId, elems: &[ir::Expr]) -> String {
        let cty = self.c_type(ty);
        let values: Vec<String> = elems.iter().map(|e| strip_parens(&self.expr(e)).to_string()).collect();
        match self.p.types.kind(ty).clone() {
            TyKind::Struct(id) if self.p.types.struct_info(id).foreign => self.foreign_aggregate(ty, elems, values),
            TyKind::Struct(id) => {
                let info = self.p.types.struct_info(id).clone();
                let parts: Vec<String> = info
                    .fields
                    .iter()
                    .zip(&values)
                    .map(|(f, v)| format!(".{} = {v}", types::field_ident(f.name.as_str())))
                    .collect();
                format!("(({cty}){{{}}})", parts.join(", "))
            }
            TyKind::Tuple(_) => {
                let parts: Vec<String> = values.iter().enumerate().map(|(i, v)| format!(".f{i} = {v}")).collect();
                format!("(({cty}){{{}}})", parts.join(", "))
            }
            TyKind::Dynamic(_) => {
                let names = ["data", "len", "cap", "allocator"];
                let parts: Vec<String> = names.iter().zip(&values).map(|(n, v)| format!(".{n} = {v}")).collect();
                format!("(({cty}){{{}}})", parts.join(", "))
            }
            TyKind::Slice(_) => {
                let parts: Vec<String> =
                    ["data", "len"].iter().zip(&values).map(|(n, v)| format!(".{n} = {v}")).collect();
                format!("(({cty}){{{}}})", parts.join(", "))
            }
            TyKind::Map(..) => format!("(({cty}){{.raw = {{{}}}}})", values.join(", ")),
            _ => format!("(({cty}){{{{{}}}}})", values.join(", ")),
        }
    }
}

struct FnCtx {
    contexts: u32,
    used_labels: HashSet<LabelId>,
    reads: HashSet<LocalId>,
    out: String,
    indent: usize,
}

fn label_name(l: LabelId) -> String {
    format!("L{}", l.0)
}

fn local_name(local: &ir::Local, id: LocalId) -> String {
    match local.name {
        Some(n) => format!("{}_{}", sanitize(n.as_str()), id.0),
        None => format!("t_{}", id.0),
    }
}

fn sanitize(name: &str) -> String {
    name.chars().map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' }).collect()
}

fn c_binop(op: ir::BinaryOp) -> &'static str {
    use ir::BinaryOp as B;
    match op {
        B::Add => "+",
        B::Sub => "-",
        B::Mul => "*",
        B::Div => "/",
        B::Rem => "%",
        B::BitAnd => "&",
        B::BitOr => "|",
        B::BitXor => "^",
        B::Shl => "<<",
        B::Shr => ">>",
        B::Eq => "==",
        B::Ne => "!=",
        B::Lt => "<",
        B::Le => "<=",
        B::Gt => ">",
        B::Ge => ">=",
        B::And => "&&",
        B::Or => "||",
        B::Pow => "**",
        B::Cmp => "<=>",
    }
}

/// Removes one layer of redundant outer parentheses. Parentheses around a
/// comma expression are kept, since removing them would split it.
fn strip_parens(s: &str) -> &str {
    let bytes = s.as_bytes();
    if bytes.first() != Some(&b'(') || bytes.last() != Some(&b')') {
        return s;
    }
    let mut depth = 0i32;
    let mut quote: Option<u8> = None;
    let mut escaped = false;
    for (i, &b) in bytes.iter().enumerate() {
        if let Some(q) = quote {
            if escaped {
                escaped = false;
            } else if b == b'\\' {
                escaped = true;
            } else if b == q {
                quote = None;
            }
            continue;
        }
        match b {
            b'"' | b'\'' => quote = Some(b),
            b'(' | b'{' | b'[' => depth += 1,
            b',' if depth == 1 => return s,
            b')' | b'}' | b']' => {
                depth -= 1;
                if depth == 0 && i != bytes.len() - 1 {
                    return s;
                }
            }
            _ => {}
        }
    }
    &s[1..s.len() - 1]
}

/// The name generated C calls a function by: the alias of an `@[extern]`
/// function no header declares, the C name of one a header does, or the
/// exported or internal name of a Wid function.
fn call_name(f: &ir::Function) -> String {
    match (&f.foreign, &f.c_call) {
        (Some(symbol), None) if !symbol.starts_with("wid_") => extern_alias(symbol),
        (Some(symbol), _) => symbol.clone(),
        (None, _) => f.export.clone().unwrap_or_else(|| f.c_name.clone()),
    }
}

/// The C name an `@[extern]` function is declared under.
fn extern_alias(symbol: &str) -> String {
    let safe: String = symbol.chars().map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' }).collect();
    format!("wid_extern_{safe}")
}

/// Formats bytes as a C string literal.
pub fn c_string_literal(bytes: &[u8]) -> String {
    let mut out = String::from("\"");
    for &b in bytes {
        match b {
            b'"' => out.push_str("\\\""),
            b'\\' => out.push_str("\\\\"),
            b'\n' => out.push_str("\\n"),
            b'\t' => out.push_str("\\t"),
            b'\r' => out.push_str("\\r"),
            0x20..=0x7e => out.push(b as char),
            _ => {
                let _ = write!(out, "\\{:03o}", b);
            }
        }
    }
    out.push('"');
    out
}

fn float_literal(v: f64, kind: FloatTy) -> String {
    if v.is_nan() {
        return "NAN".into();
    }
    if v.is_infinite() {
        return if v < 0.0 { "(-INFINITY)".into() } else { "INFINITY".into() };
    }
    match kind {
        FloatTy::F32 => {
            let mut s = format!("{:?}", v as f32);
            if !s.contains(['.', 'e', 'E']) {
                s.push_str(".0");
            }
            format!("{s}f")
        }
        FloatTy::F64 => {
            let mut s = format!("{v:?}");
            if !s.contains(['.', 'e', 'E']) {
                s.push_str(".0");
            }
            s
        }
    }
}

fn visit_block(block: &ir::Block, f: &mut impl FnMut(&ir::Expr)) {
    for s in &block.stmts {
        visit_stmt(s, f);
    }
}

fn visit_stmt(stmt: &Stmt, f: &mut impl FnMut(&ir::Expr)) {
    match stmt {
        Stmt::Let { init: Some(e), .. } | Stmt::Expr(e) | Stmt::Return(Some(e)) => visit_expr(e, f),
        Stmt::Assign { target, value } => {
            visit_expr(target, f);
            visit_expr(value, f);
        }
        Stmt::If { cond, then, else_ } => {
            visit_expr(cond, f);
            visit_block(then, f);
            visit_block(else_, f);
        }
        Stmt::Loop { body, .. } | Stmt::Labeled { body, .. } | Stmt::Scope(body) | Stmt::WithContext(body) => {
            visit_block(body, f)
        }
        _ => {}
    }
}

fn visit_expr(e: &ir::Expr, f: &mut impl FnMut(&ir::Expr)) {
    f(e);
    match &e.kind {
        ExprKind::Field { base, .. } => visit_expr(base, f),
        ExprKind::Deref(x)
        | ExprKind::AddrOf(x)
        | ExprKind::Unary { expr: x, .. }
        | ExprKind::Cast { expr: x, .. }
        | ExprKind::OptSome(x)
        | ExprKind::OptIsSome(x)
        | ExprKind::OptGet(x)
        | ExprKind::UnionTag(x)
        | ExprKind::UnionWrap { value: x, .. }
        | ExprKind::UnionGet { value: x, .. } => visit_expr(x, f),
        ExprKind::Index { base, index, .. } => {
            visit_expr(base, f);
            visit_expr(index, f);
        }
        ExprKind::SliceOf { base, lo, hi, .. } => {
            visit_expr(base, f);
            visit_expr(lo, f);
            visit_expr(hi, f);
        }
        ExprKind::Call { args, .. } | ExprKind::Builtin { args, .. } | ExprKind::Aggregate(args) => {
            for a in args {
                visit_expr(a, f);
            }
        }
        ExprKind::CallIndirect { callee, args, .. } => {
            visit_expr(callee, f);
            for a in args {
                visit_expr(a, f);
            }
        }
        ExprKind::Binary { lhs, rhs, .. } => {
            visit_expr(lhs, f);
            visit_expr(rhs, f);
        }
        ExprKind::Select { cond, then, else_ } => {
            visit_expr(cond, f);
            visit_expr(then, f);
            visit_expr(else_, f);
        }
        _ => {}
    }
}

fn collect_gotos(block: &ir::Block, out: &mut HashSet<LabelId>) {
    for s in &block.stmts {
        match s {
            Stmt::Goto(l) => {
                out.insert(*l);
            }
            Stmt::If { then, else_, .. } => {
                collect_gotos(then, out);
                collect_gotos(else_, out);
            }
            Stmt::Loop { body, .. } | Stmt::Labeled { body, .. } | Stmt::Scope(body) | Stmt::WithContext(body) => {
                collect_gotos(body, out)
            }
            _ => {}
        }
    }
}

/// Collects locals that are read somewhere (not merely assigned). Writing
/// a field or an element of a local stored in place (`a_0.data[i] = v`)
/// doesn't read it, and gcc reports a local or parameter that is only
/// written as "set but not used".
fn collect_reads(block: &ir::Block, types: &TypeTable, out: &mut HashSet<LocalId>) {
    for s in &block.stmts {
        collect_reads_stmt(s, types, out);
    }
}

fn collect_reads_stmt(stmt: &Stmt, types: &TypeTable, out: &mut HashSet<LocalId>) {
    let add = |e: &ir::Expr, out: &mut HashSet<LocalId>| {
        visit_expr(e, &mut |x| {
            if let ExprKind::Local(l) = x.kind {
                out.insert(l);
            }
        })
    };
    match stmt {
        Stmt::Let { init: Some(e), .. } | Stmt::Expr(e) | Stmt::Return(Some(e)) => add(e, out),
        Stmt::Assign { target, value } => {
            if target.written_local(types).is_some() {
                // Only the indexes on the way to the local are read.
                let mut place = target;
                loop {
                    match &place.kind {
                        ExprKind::Field { base, .. }
                        | ExprKind::OptGet(base)
                        | ExprKind::UnionGet { value: base, .. } => place = base,
                        ExprKind::Index { base, index, .. } => {
                            add(index, out);
                            place = base;
                        }
                        _ => break,
                    }
                }
            } else {
                add(target, out);
            }
            add(value, out);
        }
        Stmt::If { cond, then, else_ } => {
            add(cond, out);
            collect_reads(then, types, out);
            collect_reads(else_, types, out);
        }
        Stmt::Loop { body, .. } | Stmt::Labeled { body, .. } | Stmt::Scope(body) | Stmt::WithContext(body) => {
            collect_reads(body, types, out)
        }
        _ => {}
    }
}
