gemfile: Gemfile

PreCommit:
  BundleCheck:
    enabled: true

  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'standardrb'] # Invoke within Bundler context

  TrailingWhitespace:
    enabled: true

  YamlSyntax:
    enabled: true

PrePush:
  Tldr:
    enabled: true
    command: ['bin/tldr']
    include: 'test/**/test_*.rb'
