PreCommit:
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'standardrb'] # Invoke within Bundler context

PrePush:
  Minitest:
    enabled: true
    command: ['ruby', '-Ilib:spec', '-rminitest', "-e 'exit! Minitest.run'"]
    include: 'spec/**/*_spec.rb'
