//! The parsed program handed to the checker by the driver.

use std::collections::HashMap;
use std::path::PathBuf;

use wid_syntax::ast;

/// Identifies a package in [`ProgramInput::packages`].
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, PartialOrd, Ord, Default)]
pub struct PackageId(pub u32);

/// Every package of one program, with imports already resolved.
#[derive(Debug)]
pub struct ProgramInput {
    /// The packages; the root package is listed first.
    pub packages: Vec<PackageInput>,
    /// Build options that affect checking and lowering.
    pub options: CheckOptions,
    /// The `core:builtin` package, whose public names every file can use
    /// without importing it.
    pub prelude: Option<PackageId>,
}

/// One package (a directory of `.wid` files).
#[derive(Debug)]
pub struct PackageInput {
    /// The package name used for qualification, e.g. `fmt`.
    pub name: String,
    /// The import path, e.g. `core:fmt`, or `.` for the root.
    pub path: String,
    /// The package directory.
    pub dir: PathBuf,
    /// The parsed files.
    pub files: Vec<FileInput>,
    /// Extra C/C++ files found in the directory.
    pub c_sources: Vec<PathBuf>,
    /// For a package generated by `cimport`, how its declarations map back
    /// to C.
    pub cimport: Option<CBinding>,
}

/// What the checker needs to know about a package that `cimport` generated
/// from a C header. The package itself is ordinary Wid source (what
/// `wid cimport --dump` prints); this records what that source can't say.
#[derive(Debug, Default)]
pub struct CBinding {
    /// The header as written after `#include`: `"/abs/path.h"` or `<name.h>`.
    pub include: String,
    /// `NAME` or `NAME=value` macros defined before every inclusion.
    pub defines: Vec<String>,
    /// The macro that makes a header-only library emit its implementation.
    pub implement: Option<String>,
    /// Libraries to link, from `link:` and `pkg_config:`.
    pub link_libs: Vec<String>,
    /// Extra C compiler flags, from `include_dirs:` and `pkg_config:`.
    pub c_flags: Vec<String>,
    /// Extra linker flags, from `link:` and `pkg_config:`.
    pub link_flags: Vec<String>,
    /// The `cimport` item that created the package: its package, file and
    /// item index. `types:` is resolved in that file's scope.
    pub origin: (PackageId, usize, usize),
    /// Imported functions, by Wid name.
    pub functions: HashMap<String, CFunction>,
    /// Imported structs and unions, by Wid name.
    pub records: HashMap<String, CRecord>,
    /// Macros and constant globals that C reads by name, by Wid name.
    pub values: HashMap<String, CSlot>,
    /// The Wid name of every imported record, by its C spelling.
    pub record_names: HashMap<String, String>,
    /// Declarations that could not be imported, for error messages.
    pub skipped: Vec<CSkipped>,
    /// Where C declares each imported declaration, by Wid name, as
    /// `file:line` (for `wid doc`).
    pub locations: HashMap<String, String>,
    /// Functions declared anywhere in the header's translation unit (the C
    /// library included) that an `@[extern]` method of the program names, by
    /// C name.
    pub externs: HashMap<String, CFunction>,
}

/// An imported C function.
#[derive(Clone, Debug)]
pub struct CFunction {
    /// The C name.
    pub c_name: String,
    /// The parameters.
    pub params: Vec<CSlot>,
    /// The return type; `None` for `void`.
    pub ret: Option<CSlot>,
    /// Takes `...`.
    pub variadic: bool,
}

/// An imported C struct or union.
#[derive(Clone, Debug)]
pub struct CRecord {
    /// How C spells the type: `Color` or `struct rAudioBuffer`.
    pub c_type: String,
    /// `sizeof`, or 0 for an opaque record.
    pub size: u64,
    /// `alignof`, or 0 for an opaque record.
    pub align: u64,
    /// The fields, by name.
    pub fields: HashMap<String, CSlot>,
    /// Fields that could not be imported, by C name, with the reason.
    pub skipped_fields: Vec<(String, String)>,
}

/// A C type in a parameter, return value, field or named value.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CSlot {
    /// How C spells the type, for casts: `const char *`, `Vector2`.
    pub c_type: String,
    /// The C spelling of the record passed by value, when it is one; a
    /// `types:` mapping converts it with `memcpy`.
    pub record: Option<String>,
    /// Whether the type is a C array (a field such as `float m[16]`).
    pub array: bool,
    /// Whether the type is a data or function pointer.
    pub pointer: bool,
}

/// A C declaration `cimport` could not turn into Wid.
#[derive(Clone, Debug)]
pub struct CSkipped {
    /// The C name.
    pub c_name: String,
    /// The name it would have had in Wid.
    pub wid_name: String,
    /// The other names a use may spell it with: what the naming rules for
    /// functions, types and constants make of the C name (`counter`,
    /// `Counter` and `COUNTER` for `lib_counter`), so that each one is
    /// explained, not just `wid_name`.
    pub spellings: Vec<String>,
    /// Why it was skipped, as a sentence fragment: "is a function-like macro".
    pub reason: String,
    /// Where C declares it, as `file:line`.
    pub location: String,
    /// The other C declarations that would get the same Wid name, when
    /// that is why it was left out.
    pub collides_with: Vec<String>,
}

/// One parsed file.
#[derive(Debug)]
pub struct FileInput {
    /// The syntax tree.
    pub ast: ast::File,
    /// For each `import` and `cimport` item, by the byte offset where the
    /// item starts, the imported package.
    pub imports: HashMap<u32, PackageId>,
    /// The source text, for messages that quote code.
    pub text: std::sync::Arc<str>,
    /// The file's path as messages show it.
    pub display: String,
    /// Errors from loading the imports inside `comptime if` branches, keyed
    /// like `imports`. They are reported only when the branch is chosen.
    pub deferred: HashMap<u32, Vec<wid_diagnostics::Diagnostic>>,
    /// The parser's E0113 errors for struct literal syntax (`Vec2{x: 1}`),
    /// which the checker reports: their fix calls `new`, and for a type
    /// without one (`Int{1}`) the checker fits the error to the type.
    pub struct_literals: Vec<wid_diagnostics::Diagnostic>,
}

/// Options that affect checking.
#[derive(Clone, Debug)]
pub struct CheckOptions {
    /// Emit bounds checks.
    pub bounds_checks: bool,
    /// Trap on integer overflow.
    pub overflow_checks: bool,
    /// The target operating system (`darwin`, `linux`, `windows`).
    pub os: String,
    /// The target architecture (`arm64`, `amd64`).
    pub arch: String,
    /// `-define:NAME=value` constants.
    pub defines: HashMap<String, String>,
    /// Whether this is a debug build.
    pub debug: bool,
    /// Whether tests are being built (`wid test`).
    pub testing: bool,
    /// Check every function in non-root packages too.
    pub check_all_packages: bool,
    /// Check the root package as a library, for tools like `wid doc`:
    /// `def main` is optional.
    pub library: bool,
}

/// Operating systems `-target:` accepts, as the prelude's `Os` names them.
pub const TARGET_OSES: &[&str] = &["darwin", "linux", "windows", "freebsd", "openbsd", "netbsd", "freestanding"];

/// Architectures `-target:` accepts, as the prelude's `Arch` names them.
pub const TARGET_ARCHES: &[&str] = &["arm64", "amd64", "i386", "arm32", "riscv64", "wasm32", "wasm64"];

/// The operating system the compiler runs on.
pub fn host_os() -> String {
    std::env::consts::OS.replace("macos", "darwin")
}

/// The architecture the compiler runs on.
pub fn host_arch() -> String {
    match std::env::consts::ARCH {
        "aarch64" => "arm64".into(),
        "x86_64" => "amd64".into(),
        "x86" => "i386".into(),
        "arm" => "arm32".into(),
        other => other.into(),
    }
}

/// Parses `os_arch`, like `linux_amd64`.
pub fn parse_target(text: &str) -> Result<(String, String), String> {
    let (os, arch) = text
        .split_once('_')
        .ok_or_else(|| format!("write the target as `os_arch`, like `-target:{}_{}`", host_os(), host_arch()))?;
    if !TARGET_OSES.contains(&os) {
        return Err(format!("unknown operating system `{os}`; use one of {}", TARGET_OSES.join(", ")));
    }
    if !TARGET_ARCHES.contains(&arch) {
        return Err(format!("unknown architecture `{arch}`; use one of {}", TARGET_ARCHES.join(", ")));
    }
    Ok((os.to_string(), arch.to_string()))
}

impl Default for CheckOptions {
    fn default() -> Self {
        CheckOptions {
            bounds_checks: true,
            overflow_checks: false,
            os: host_os(),
            arch: host_arch(),
            defines: HashMap::new(),
            debug: false,
            testing: false,
            check_all_packages: false,
            library: false,
        }
    }
}
