#!/usr/bin/env ruby -w

require_relative "../lib/wid"
require "open3"

if ARGV.size != 1
  puts "Usage: #{$0} <file>"
  exit 1
end

ROOT = File.expand_path(File.join(File.dirname(__FILE__), ".."))

file = ARGV[0]

puts "/**"
puts " * Compiling #{file}..."
puts " **/"
system("bat", "--language", "ruby", file)

input = File.read(file)
output = Wid::Compiler.compile(input)

CC = ENV["CC"] || "/opt/homebrew/bin/zig cc"
FLAGS = %W[
  -v
  -std=c2x
  -I#{ROOT}/include
]

basename = File.basename(file, ".*")
src = File.join(Dir.pwd, "#{basename}.c")
exe = File.join(Dir.pwd, basename)

File.write(src, output)

puts "/**"
puts " * Compiling #{src}..."
puts " **/"
system("bat", src)

cmd = [*CC.split(" "), *FLAGS, src, "-o", exe]

Open3.popen3(*cmd) do |stdin, stdout, stderr, wait_thr|
  stdin.close
  stdout.each do |line|
    puts line
  end
  stderr.each do |line|
    puts line
  end
  exit_status = wait_thr.value
  exit exit_status.exitstatus if exit_status.exitstatus != 0
end

puts "/**"
puts " * Executing #{exe}..."
puts " **/"
system(exe)

exit 0
