# frozen_string_literal: true

# rbs_inline: enabled
#
# --- DO NOT EDIT THIS FILE ---
#
# This file was generated by `rake` from lib/wid/ast/node/node.rb.erb.
#
# Check the definition at lib/wid/ast/nodes.yml.
#
# Generated at: 2024-11-01 13:32:05 +0100

module Wid
  module AST
    class Node
      class Float < Node
        attr_reader :value # : Float

        # @rbs value: Float
        # @rbs return: void
        def initialize(value:)
          @value = value
        end

        def to_h
          super.merge(value: @value)
        end
      end
    end
  end
end
