# frozen_string_literal: true

# rbs_inline: enabled
#
# --- DO NOT EDIT THIS FILE ---
#
# This file was generated by `rake` from lib/wid/ast/node/node.rb.erb.
#
# Check the definition at lib/wid/ast/nodes.yml.

module Wid
  module AST
    class Node
      class Grouping < Node
        attr_reader :expression # : Node

        # @rbs expression: Node
        # @rbs return: void
        def initialize(expression:)
          @expression = expression
        end

        # @rbs visitor: Visitor -> void
        def accept(visitor)
          visitor.visit_grouping_node(self)
        end

        # @rbs return: Hash[Symbol, Node]
        def to_h
          super.merge(expression: @expression.to_h)
        end
      end
    end
  end
end
