# frozen_string_literal: true

# rbs_inline: enabled
#
# --- DO NOT EDIT THIS FILE ---
#
# This file was generated by `rake` from lib/wid/ast/node/node.rb.erb.
#
# Check the definition at lib/wid/ast/nodes.yml.

module Wid
  module AST
    class Node
      class Integer < Node
        attr_reader :value # : Integer

        # @rbs value: Integer
        # @rbs return: void
        def initialize(value:)
          @value = value
        end

        # @rbs visitor: Visitor -> void
        def accept(visitor)
          visitor.visit_integer_node(self)
        end

        # @rbs return: Hash[Symbol, Integer]
        def to_h
          super.merge(value: @value)
        end
      end
    end
  end
end
