# frozen_string_literal: true

# rbs_inline: enabled
#
# --- DO NOT EDIT THIS FILE ---
#
# This file was generated by `rake` from lib/wid/ast/node/node.rb.erb.
#
# Check the definition at lib/wid/ast/nodes.yml.
#
# Generated at: 2024-11-01 13:32:05 +0100

module Wid
  module AST
    class Node
      class Nil < Node
      end
    end
  end
end
