# frozen_string_literal: true

# rbs_inline: enabled
#
# --- DO NOT EDIT THIS FILE ---
#
# This file was generated by `rake` from lib/wid/ast/node/node.rb.erb.
#
# Check the definition at lib/wid/ast/nodes.yml.

module Wid
  module AST
    class Node
      class Nil < Node
        # @rbs visitor: Visitor -> void
        def accept(visitor)
          visitor.visit_nil_node(self)
        end
      end
    end
  end
end
