# frozen_string_literal: true

# rbs_inline: enabled
#
# --- DO NOT EDIT THIS FILE ---
#
# This file was generated by `rake` from lib/wid/ast/node/node.rb.erb.
#
# Check the definition at lib/wid/ast/nodes.yml.

module Wid
  module AST
    class Node
      class Print < Node
        attr_reader :expressions # : Array[Node]

        # @rbs expressions: Array[Node]
        # @rbs return: void
        def initialize(expressions:)
          @expressions = expressions
        end

        # @rbs visitor: Visitor -> void
        def accept(visitor)
          visitor.visit_print_node(self)
        end

        # @rbs return: Hash[Symbol, Array[Node]]
        def to_h
          super.merge(expressions: @expressions.map(&:to_h))
        end
      end
    end
  end
end
