# frozen_string_literal: true

# rbs_inline: enabled
#
# --- DO NOT EDIT THIS FILE ---
#
# This file was generated by `rake` from lib/wid/ast/node/node.rb.erb.
#
# Check the definition at lib/wid/ast/nodes.yml.

module Wid
  module AST
    class Node
      class Program < Node
        attr_reader :statements # : Array[Node]

        # @rbs statements: Array[Node]
        # @rbs return: void
        def initialize(statements:)
          @statements = statements
        end

        # @rbs visitor: Visitor -> void
        def accept(visitor)
          visitor.visit_program_node(self)
        end

        # @rbs return: Hash[Symbol, Array[Node]]
        def to_h
          super.merge(statements: @statements.map(&:to_h))
        end
      end
    end
  end
end
