# frozen_string_literal: true

# rbs_inline: enabled
#
# --- DO NOT EDIT THIS FILE ---
#
# This file was generated by `rake` from lib/wid/ast/node/node.rb.erb.
#
# Check the definition at lib/wid/ast/nodes.yml.

module Wid
  module AST
    class Node
      class Statements < Node
        attr_reader :body # : Array[Node]

        # @rbs body: Array[Node]
        # @rbs return: void
        def initialize(body:)
          @body = body
        end

        # @rbs visitor: Visitor -> void
        def accept(visitor)
          visitor.visit_statements_node(self)
        end

        # @rbs return: Hash[Symbol, Array[Node]]
        def to_h
          super.merge(body: @body.map(&:to_h))
        end
      end
    end
  end
end
