# frozen_string_literal: true

# rbs_inline: enabled
#
# --- DO NOT EDIT THIS FILE ---
#
# This file was generated by `rake` from lib/wid/ast/node/node.rb.erb.
#
# Check the definition at lib/wid/ast/nodes.yml.

module Wid
  module AST
    class Node
      class String < Node
        attr_reader :unescaped # : String

        # @rbs unescaped: String
        # @rbs return: void
        def initialize(unescaped:)
          @unescaped = unescaped
        end

        # @rbs visitor: Visitor -> void
        def accept(visitor)
          visitor.visit_string_node(self)
        end

        # @rbs return: Hash[Symbol, String]
        def to_h
          super.merge(unescaped: @unescaped)
        end
      end
    end
  end
end
