# frozen_string_literal: true

# rbs_inline: enabled
#
# --- DO NOT EDIT THIS FILE ---
#
# This file was generated by `rake` from lib/wid/ast/node/node.rb.erb.
#
# Check the definition at lib/wid/ast/nodes.yml.

module Wid
  module AST
    class Node
      class Unary < Node
        attr_reader :operator # : Symbol
        attr_reader :right # : Node

        # @rbs operator: Symbol
        # @rbs right: Node
        # @rbs return: void
        def initialize(operator:, right:)
          @operator = operator
          @right = right
        end

        # @rbs visitor: Visitor -> void
        def accept(visitor)
          visitor.visit_unary_node(self)
        end

        # @rbs return: Hash[Symbol, Symbol | Node]
        def to_h
          super.merge(operator: @operator, right: @right.to_h)
        end
      end
    end
  end
end
